
hello: hello.c
	gcc hello.c -o hello -std=c99 -Wall

cnhello: cnhello.c
	gcc cnhello.c -o cnhello -std=c99 -Wall

triangle: triangle.c
	gcc triangle.c -o triangle -std=c99 -Wall

circle: circle.c
	gcc circle.c -o circle -std=c99 -Wall

task1: task1.c
	gcc task1.c -o task1 -std=c99 -Wall

task2a: task2a.c
	gcc task2a.c -o task2a -std=c99 -Wall

task2b: task2b.c
	gcc task2b.c -o task2b -std=c99 -Wall

task3: task3a.c
	gcc task3a.c -o task3a -std=c99 -Wall

task4: task4.c
	gcc task4.c -o task4 -std=c99 -Wall

task5: task5.c
	gcc task5.c -o task5 -std=c99 -Wall